### ISSUE TITLE
Remove tokio dependency?

### ISSUE THREAD

**Issue by daladim** [daladim/kitchen-fridge#2]
`tokio` is required in many tests and examples.

However, very few features of the lib depend on tokio. Maybe they could be replaced by non-tokio equivalents so that `tokio` could become a dev-dependency only. This may(?) give a choice to end-users to use kitchen-fridge in both their `tokio` or `async-std` applications

**Comment by tippfehlr** [comment]
I'm currently learning rust by writing a todo list with tauri that syncs over caldav tasks, so I'm a complete noob.
If I understand correctly, this is the reason I cannot use Provider::sync() in a [tauri command](https://tauri.app/v1/guides/features/command/#async-commands), right?

**Comment by daladim** [comment]
Hello.
I don't know tauri (yet?), but I might help you in case you give the exact error you're facing.

**Comment by daladim** [comment]
Note: I thought that `tokio` could be removed as a dependency, because code from this library uses the concept of `async`/`await` without really using `tokio` utilities, and that it could probably be used either from `tokio`, `async-std`or even other async frameworks.

I've just checked using kitchen-fridge from an `async-std` example.
 It builds fine, but it crashes at runtime with `thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'`, because dependencies of `kitchen_fridge` (e.g. `hyper`) _require_ being run from a `tokio` context.

@tippf3hlr , if that's the error you're facing, you won't be able to use `kitchen_fridge` in your non-tokio app I'm afraid. If that's a different error, we may have a look if you want

**Comment by tippfehlr** [comment]
Thanks for trying it out, I was not expecting that.
My problem is solved now, but I can't exactly say what the problem was anymore. 
As I said I'm really new to rust and didn't bother to learn basic concepts of the language :)

**Comment by daladim** [comment]
All right, happy coding in Rust then :)

I'm closing this issue as it is not applicable after all
